from sqlalchemy import Column, String, Integer, Numeric, Date, TIMESTAMP

from app.database.db_connection import Base


class LctoProdutosPDV(Base):
    __tablename__ = "lctoprodutos_pdv"
    __table_args__ = {"schema": "pdv"}

    lcpr_numabertura = Column(String(16), nullable=True)
    lcpr_codempresa = Column(String(3), primary_key=True)
    lcpr_situacao = Column(String(1), nullable=True)
    lcpr_statusvenda = Column(String(1), nullable=True)
    lcpr_pdv = Column(String(3), primary_key=True)
    lcpr_ecf = Column(String(3), nullable=True)
    lcpr_cupom = Column(String(9), primary_key=True)
    lcpr_datamvto = Column(Date, primary_key=True)
    lcpr_dcto = Column(Integer, nullable=True)
    lcpr_cfop = Column(String(4), nullable=True)
    lcpr_codentidade = Column(Integer, nullable=True)
    lcpr_cnpjcpf = Column(String(14), nullable=True)
    lcpr_serie = Column(String(3), primary_key=True)
    lcpr_modelo = Column(String(2), nullable=True)
    lcpr_totalprodutos = Column(Numeric(18,5), nullable=True)
    lcpr_descontos = Column(Numeric(18,5), nullable=True)
    lcpr_acrescimos = Column(Numeric(18,5), nullable=True)
    lcpr_totaldcto = Column(Numeric(18,5), nullable=True)
    lcpr_chavenfce = Column(String(44), nullable=True)
    lcpr_protocolonfce = Column(String(20), nullable=True)
    lcpr_protocolocancnfce = Column(String(20), nullable=True)
    lcpr_valtribaprox = Column(Numeric(18,5), nullable=True)
    lcpr_perctribaprox = Column(Numeric(18,5), nullable=True)
    lcpr_tribfederal = Column(Numeric(18,5), nullable=True)
    lcpr_tribestadual = Column(Numeric(18,5), nullable=True)
    lcpr_bcicms = Column(Numeric(18,5), nullable=True)
    lcpr_icms = Column(Numeric(18,5), nullable=True)
    lcpr_bcpis = Column(Numeric(18,5), nullable=True)
    lcpr_pis = Column(Numeric(18,5), nullable=True)
    lcpr_bcconfins = Column(Numeric(18,5), nullable=True)
    lcpr_cofins = Column(Numeric(18,5), nullable=True)
    lcpr_datahoraemiss = Column(TIMESTAMP, nullable=True)
    lcpr_datahoracanc = Column(TIMESTAMP, nullable=True)
    lcpr_supervisorcanc = Column(Integer, nullable=True)
    lcpr_operadorcanc = Column(Integer, nullable=True)
    lcpr_countautorizacao = Column(Integer, nullable=True)
    lcpr_datahora = Column(String(20), nullable=True)
    lcpr_nomeentidade = Column(String(50), nullable=True)
    lcpr_codvendedor = Column(String(3), nullable=True)
    lcpr_chavecanccfe = Column(String(44), nullable=True)
    lcpr_tipoemissao = Column(String(1), nullable=True)
    lcpr_idpedidos = Column(String(100), nullable=True)
    lcpr_scantechvnd = Column(Integer, nullable=True)
    lcpr_scantechfpv = Column(Integer, nullable=True)
    lcpr_cnpjcpfclubedesc = Column(String(14), nullable=True)
    lcpr_cashback = Column(Numeric(18,5), nullable=True)
    lcpr_codoperadorpdv = Column(String(3), nullable=True)
    lcpd_valorfcp = Column(Numeric(18,5), nullable=True)
    lcpr_valorfcp = Column(Numeric(18,5), nullable=True)
    lcpr_envcashback = Column(String(1), nullable=True)
    lcpr_dtenvcashback = Column(Date, nullable=True)
    lcpr_cnpjcpfcashback = Column(String(14), nullable=True)
    lcpr_envcashbackcanc = Column(String(1), nullable=True)
