# app/models/empresa_model.py
from sqlalchemy import Column, String, Integer, Date
from app.database.db_connection import Base  # certifique-se de ter o Base

class Empresa(Base):
    __tablename__ = "empresas"

    empr_codigo = Column(String(3), primary_key=True)
    empr_codgrupo = Column(String(2))
    empr_nome = Column(String(100))
    empr_nomereduzido = Column(String(20))
    empr_razaosocial = Column(String(100))
    empr_cnpjcpf = Column(String(14))
    empr_atividade = Column(String(1))
    empr_codqualificacao = Column(String(2))
    empr_inscricaoestadual = Column(String(20))
    empr_inscricaomunicipal = Column(String(20))
    empr_responsavel = Column(String(50))
    empr_cpfresponsavel = Column(String(11))
    empr_cargoresponsavel = Column(String(20))
    empr_endereco = Column(String(100))
    empr_complemento = Column(String(100))
    empr_numero = Column(Integer)
    empr_bairro = Column(String(20))
    empr_codmunicipio = Column(String(4))
    empr_municipio = Column(String(50))
    empr_uf = Column(String(2))
    empr_cep = Column(String(8))
    empr_fone = Column(String(13))
    empr_fax = Column(String(12))
    empr_email = Column(String(50))
    empr_contnome = Column(String(50))
    empr_contcnpj = Column(String(14))
    empr_contcpf = Column(String(11))
    empr_contcrc = Column(String(15))
    empr_contendereco = Column(String(100))
    empr_contcomplemento = Column(String(100))
    empr_contnumero = Column(Integer)
    empr_contbairro = Column(String(20))
    empr_contcodmunicipio = Column(String(4))
    empr_contmunicipio = Column(String(50))
    empr_contuf = Column(String(2))
    empr_contcep = Column(String(8))
    empr_contfone = Column(String(13))
    empr_contfax = Column(String(12))
    empr_contemail = Column(String(50))
    empr_regjuntacomercial = Column(String(20))
    empr_dtdespacho = Column(Date)
    empr_rntrc = Column(String(20))
    empr_inscricaost = Column(String(20))
    empr_infsociais = Column(String(50))
    empr_situacao = Column(String(1))  # Aqui deve ser "A" ou "I" (ativo/inativo)
    empr_crt = Column(String(1))
    empr_numfuncionarios = Column(Integer)
    empr_consultadfe = Column(String(1))
    empr_synccrm = Column(String(1))
