from sqlalchemy import Column, String, Integer, Date, Numeric, TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class LctoProdutosPUBLIC(Base):
    __tablename__ = "lctoprodutos"
    __table_args__ = {"schema": "public"}

    # Definindo chaves primárias compostas conforme padrão PDV
    lcpr_codempresa = Column(String(3), primary_key=True)
    lcpr_dtmvto = Column(Date, primary_key=True)
    lcpr_pdv = Column(String(3), primary_key=True)
    lcpr_cupom = Column(String(9), primary_key=True)
    lcpr_seriedcto = Column(String(3), primary_key=True)

    # Demais colunas
    lcpr_protocolo = Column(String(16))
    lcpr_chave = Column(String(16))
    lcpr_situacao = Column(String(1))
    lcpr_dtlcto = Column(Date)
    lcpr_dtemissao = Column(Date)
    lcpr_codentidade = Column(Integer)
    lcpr_cnpjcpf = Column(String(14))
    lcpr_codendereco = Column(Integer)
    lcpr_codqualificacao = Column(String(2))
    lcpr_uf = Column(String(2))
    lcpr_codespecie = Column(String(4))
    lcpr_dcto = Column(Integer)
    lcpr_codprocesso = Column(String(4))
    lcpr_tipoprocesso = Column(String(2))
    lcpr_modelodcto = Column(String(3))
    lcpr_es = Column(String(1))
    lcpr_cfop = Column(String(20))
    lcpr_codvendedor = Column(String(3))
    lcpr_codtransportador = Column(String(3))
    lcpr_codfpgto = Column(String(3))
    lcpr_bcicms = Column(Numeric(18, 5))
    lcpr_redbcicms = Column(Numeric(18, 5))
    lcpr_icms = Column(Numeric(18, 5))
    lcpr_icmsdifalest = Column(Numeric(18, 5))
    lcpr_icmsdifalint = Column(Numeric(18, 5))
    lcpr_bcsubtrib = Column(Numeric(18, 5))
    lcpr_subtrib = Column(Numeric(18, 5))
    lcpr_bcpis = Column(Numeric(18, 5))
    lcpr_pis = Column(Numeric(18, 5))
    lcpr_bccofins = Column(Numeric(18, 5))
    lcpr_cofins = Column(Numeric(18, 5))
    lcpr_totalprodutos = Column(Numeric(18, 5))
    lcpr_tipofrete = Column(String(1))
    lcpr_frete = Column(Numeric(18, 5))
    lcpr_seguro = Column(Numeric(18, 5))
    lcpr_despesaac = Column(Numeric(18, 5))
    lcpr_ipi = Column(Numeric(18, 5))
    lcpr_desconto = Column(Numeric(18, 5))
    lcpr_funrural = Column(Numeric(18, 5))
    lcpr_totaldcto = Column(Numeric(18, 5))
    lcpr_adicionalfin = Column(Numeric(18, 5))
    lcpr_abatimentofin = Column(Numeric(18, 5))
    lcpr_outrosacrescimos = Column(Numeric(18, 5))
    lcpr_outrosabatimentos = Column(Numeric(18, 5))
    lcpr_iss = Column(Numeric(18, 5))
    lcpr_fcp = Column(Numeric(18, 5))
    lcpr_ctfiscal = Column(Numeric(18, 5))
    lcpr_ctnota = Column(Numeric(18, 5))
    lcpr_ctlogistica = Column(Numeric(18, 5))
    lcpr_ctmedio = Column(Numeric(18, 5))
    lcpr_ctoperacao = Column(Numeric(18, 5))
    lcpr_ctdesembolso = Column(Numeric(18, 5))
    lcpr_credcompra = Column(Numeric(18, 5))
    lcpr_debcompra = Column(Numeric(18, 5))
    lcpr_debvenda = Column(Numeric(18, 5))
    lcpr_ctvenda = Column(Numeric(18, 5))
    lcpr_prvenda = Column(Numeric(18, 5))
    lcpr_comissao = Column(Numeric(18, 5))
    lcpr_peso = Column(Numeric(18, 5))
    lcpr_observacao = Column(String(2000))
    lcpr_complemento = Column(String(2000))
    lcpr_alterado = Column(String(1))
    lcpr_reprocessar = Column(String(1))
    lcpr_carregamento = Column(Integer)
    lcpr_chavenfe = Column(String(44))
    lcpr_protocolonfe = Column(String(20))
    lcpr_protocolocancnfe = Column(String(20))
    lcpr_protocoloencerramento = Column(String(20))
    lcpr_protocoloacordo = Column(String(16))
    lcpr_codremetente = Column(Integer)
    lcpr_codexpedidor = Column(Integer)
    lcpr_coddestinatario = Column(Integer)
    lcpr_codrecebedor = Column(Integer)
    lcpr_codseguro = Column(Integer)
    lcpr_codtomador = Column(String(1))
    lcpr_nsu = Column(Integer)
    lcpr_protocolomanifestacao = Column(String(15))
    lcpr_volumes = Column(Numeric(18, 5))
    lcpr_tipovolumes = Column(String(20))
    lcpr_abertura = Column(Integer)
    lcpr_pesobruto = Column(Numeric(18, 5))
    lcpr_pesoliquido = Column(Numeric(18, 5))
    lcpr_protocoloreferenciado = Column(String(16))
    lcpr_nsureferenciado = Column(Integer)
    lcpr_protocolovenda = Column(String(16))
    lcpr_chavenfereferenciado = Column(String(44))
    lcpr_chavecteanulacao = Column(String(44))
    lcpr_pedido = Column(String(200))
    lcpr_estacao = Column(String(3))
    lcpr_modal = Column(String(2))
    lcpr_tpservico = Column(String(1))
    lcpr_cst = Column(String(3))
    lcpr_alicms = Column(Numeric(18, 5))
    lcpr_codveiculo = Column(Integer)
    lcpr_codmotorista = Column(Integer)
    lcpr_valorpedagio = Column(Numeric(18, 5))
    lcpr_enviado = Column(String(1))
    lcpr_acrescimopdv = Column(Numeric(18, 5))
    lcpr_descontopdv = Column(Numeric(18, 5))
    lcpr_abatcompra = Column(Numeric(18, 5))
    lcpr_codoperadorpdv = Column(String(3))
    lcpr_fcpconsfinal = Column(String(1))
    lcpr_recfisicoforcado = Column(String(1))
    lcpr_dthoralcto = Column(TIMESTAMP)
    lcpr_codenderecoretirada = Column(Integer)
    lcpr_codenderecoentrega = Column(Integer)
    lcpr_codusulcto = Column(String(4))
    lcpr_despactrib = Column(String(1))
